<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>traducteur</title>
</head>
<body>
    <header>
        <h1>Traducteur Anglais - Français</h1>
    </header>
	<main>

    	<form action="traducteur.php" method="POST">
	        <ul>
	        	<li>
	                <label for="word">Mot :</label>
	                <input type="text" id="word" name="word">
	            </li>
	            <li>
		            <label for="direction">Sens de traduction :</label>
		            <select id="direction" name="direction">
		            	<option value="toEnglish">Français vers Anglais</option>
		            	<option value="toFrench">Anglais vers Français</option>
		            </select>
	            </li>
	            <li>
	            	<input type="submit" value="Traduire">
	            </li>
	        </ul>
        </form>
        <?php if($result != null) { ?>
            	
                <p><?= $result ?></p>
            
            <? } ?>
    </main>
</body>
</html> 